/**
 * AI Novel Studio - Mock 风格数据（v0.6.0 更新）
 */
import type { StyleProfile } from '../../types/style';
import type { OutputProfile } from '../../types/output';
import type { Character } from '../../types/character';

export const mockStyleProfiles: StyleProfile[] = [
  {
    id: 'style-001',
    novelId: 'novel-001',
    name: '科幻快节奏',
    sourceType: 'system_default',
    description: '适合科幻小说的快节奏风格',
    targetWordsPerChapter: 4000,
    rhythmPreference: 'fast',
    dialogueRatio: 0.35,
    descriptionRatio: 0.25,
    prohibitedStyles: ['过度心理描写', '长篇景物描写'],
    isActive: true,
    createdAt: '2026-05-10T08:00:00Z',
    updatedAt: '2026-05-10T08:00:00Z',
  },
  {
    id: 'style-002',
    novelId: 'novel-001',
    name: '仙侠厚重',
    sourceType: 'system_default',
    description: '适合仙侠小说的厚重风格',
    targetWordsPerChapter: 5000,
    rhythmPreference: 'moderate',
    dialogueRatio: 0.3,
    descriptionRatio: 0.4,
    prohibitedStyles: ['现代口语', '西式表达'],
    isActive: true,
    createdAt: '2026-05-10T09:00:00Z',
    updatedAt: '2026-05-10T09:00:00Z',
  },
];

export const mockOutputProfiles: OutputProfile[] = [
  {
    id: 'output-001',
    novelId: 'novel-001',
    name: '默认输出方案',
    description: '标准章节输出配置',
    chapterWordRange: { min: 3000, max: 6000, default: 4000 },
    paragraphLength: 'medium',
    povType: 'third_person_limited',
    tenseType: 'past',
    endingHookRequired: true,
    isDefault: true,
    createdAt: '2026-05-10T10:00:00Z',
    updatedAt: '2026-05-10T10:00:00Z',
  },
  {
    id: 'output-002',
    novelId: 'novel-001',
    name: '第一人称方案',
    description: '使用第一人称视角',
    chapterWordRange: { min: 2500, max: 5000, default: 3500 },
    paragraphLength: 'medium',
    povType: 'first_person',
    tenseType: 'present',
    endingHookRequired: false,
    isDefault: false,
    createdAt: '2026-05-10T11:00:00Z',
    updatedAt: '2026-05-10T11:00:00Z',
  },
];

export const mockCharacters: Character[] = [
  {
    id: 'char-001',
    novelId: 'novel-001',
    name: '林远',
    roleType: 'protagonist',
    identity: '航天工程师',
    faction: '第七前哨站',
    relationToProtagonist: '本人',
    goal: '找到回家的方法，同时揭开第七前哨站背后的真相',
    personality: '理性冷静，善于观察和分析，但在情感表达上较为内敛',
    behaviorLimits: '不能杀人（除非自卫）',
    forbiddenBehaviors: '不能背叛朋友',
    currentState: '刚刚在第七前哨站醒来，对周围环境一无所知',
    source: 'manual',
    isActive: true,
    createdAt: '2026-05-10T08:00:00Z',
    updatedAt: '2026-05-10T08:00:00Z',
  },
  {
    id: 'char-002',
    novelId: 'novel-001',
    name: '艾琳(E-247)',
    roleType: 'supporting',
    identity: '适应指导员',
    faction: '第七前哨站',
    relationToProtagonist: '指导员',
    goal: '完成指导员职责，但内心对系统的某些做法存有疑虑',
    personality: '训练有素，情绪控制力强，在执行职责和个人良知之间存在冲突',
    behaviorLimits: '',
    forbiddenBehaviors: '不能违反前哨站指令',
    currentState: '正在引导林远适应前哨站生活',
    source: 'manual',
    isActive: true,
    createdAt: '2026-05-10T09:00:00Z',
    updatedAt: '2026-05-10T09:00:00Z',
  },
  {
    id: 'char-003',
    novelId: 'novel-001',
    name: '卡尔·雷恩',
    roleType: 'antagonist',
    identity: '安全主管',
    faction: '第七前哨站',
    relationToProtagonist: '潜在对手',
    goal: '维护前哨站的安全和传送系统的秘密',
    personality: '表面和善，实际上为了维护系统稳定可以牺牲任何人',
    behaviorLimits: '',
    forbiddenBehaviors: '不能公开违反联盟条例',
    currentState: '尚未出场，但已在暗中关注林远',
    source: 'manual',
    isActive: true,
    createdAt: '2026-05-10T10:00:00Z',
    updatedAt: '2026-05-10T10:00:00Z',
  },
];
