const E2E_ALLOWED_COMMANDS = new Set([
  'get_e2e_diagnostics',
  'get_all_novels',
  'get_novel_by_id',
  'get_chapter_by_id',
  'get_chapters_by_novel_id',
  'get_drafts_by_chapter_id',
  'count_drafts_by_chapter_id',
  'get_adopted_draft_by_chapter_id',
  'get_chapter_summary',
  'get_chapter_summaries_by_novel',
  'get_context_records',
  'get_ai_task_records_by_chapter_id',
  'list_ai_tasks',
  'get_ai_task',
  'list_agent_plans_by_chapter',
  'get_agent_plan',
  'create_agent_plan',
  'acquire_agent_plan_lease',
  'claim_agent_plan_step',
  'get_result_artifact',
  'prepare_placement_proposal',
  'get_placement_proposal',
  'apply_placement_plan',
  'get_world_settings',
  'list_faction_assets',
  'get_quality_check_issues',
  'list_quality_check_reports',
  'get_quality_check_report_snapshot',
  'get_generation_jobs_by_chapter_id',
  'get_generation_step_results',
  'get_e2e_novel_commit_state',
  'get_e2e_large_text_draft_state',
  'corrupt_e2e_large_text_chunk',
  'get_review_authorization',
  'get_e2e_agent_closed_loop_state',
  'get_task_conversation',
]);

export function isE2eBridgeCommandAllowed(command: string): boolean {
  return E2E_ALLOWED_COMMANDS.has(command);
}
